apiVersion: v1                                      # API version
kind: Service                                       # Type of kubernetes resource 
metadata:
  name: handyman-postgres                           # Name of the resource
  labels:                                           # Labels that will be applied to the resource
    app: handyman-postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:                                         # Selects any Pod with labels `app=handyman-postgres,tier=postgres`
    app: handyman-postgres
    tier: postgres