// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewService struct {
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
	Phone    string `json:"phone"`
	City     string `json:"city"`
	Address  string `json:"address"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Service struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Price       float64 `json:"price"`
	User        *User   `json:"user"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Phone   string `json:"phone"`
	City    string `json:"city"`
	Address string `json:"address"`
}
